drop table if exists quotes cascade;
create table quotes (sym varchar(128), days integer,price integer);-- Table: quotes
INSERT INTO QUOTES(sym,days,price) VALUES('MSFT',1,982);
INSERT INTO QUOTES(sym,days,price) VALUES('MSFT',2,301);
INSERT INTO QUOTES(sym,days,price) VALUES('MSFT',3,750);
INSERT INTO QUOTES(sym,days,price) VALUES('MSFT',4,960);
INSERT INTO QUOTES(sym,days,price) VALUES('MSFT',5,145);
INSERT INTO QUOTES(sym,days,price) VALUES('ERTS',1,350);
INSERT INTO QUOTES(sym,days,price) VALUES('ERTS',2,976);
INSERT INTO QUOTES(sym,days,price) VALUES('ERTS',3,487);
INSERT INTO QUOTES(sym,days,price) VALUES('ERTS',4,1);
INSERT INTO QUOTES(sym,days,price) VALUES('ERTS',5,515);
INSERT INTO QUOTES(sym,days,price) VALUES('MSN',1,517);
INSERT INTO QUOTES(sym,days,price) VALUES('MSN',2,184);
INSERT INTO QUOTES(sym,days,price) VALUES('MSN',3,810);
INSERT INTO QUOTES(sym,days,price) VALUES('MSN',4,532);
INSERT INTO QUOTES(sym,days,price) VALUES('MSN',5,457);
INSERT INTO QUOTES(sym,days,price) VALUES('IBM',1,736);
INSERT INTO QUOTES(sym,days,price) VALUES('IBM',2,555);
INSERT INTO QUOTES(sym,days,price) VALUES('IBM',3,963);
INSERT INTO QUOTES(sym,days,price) VALUES('IBM',4,924);
INSERT INTO QUOTES(sym,days,price) VALUES('IBM',5,197);
